web:
  build: .
  command: "/bin/sh -c 'rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'"
  volumes:
    - .:/rails-app
  expose:
    - 3000
  external_links:
    - elasticsearch
  volumes_from:
    - gems-2.1
  environment:
    RAILS_ENV: development
    VIRTUAL_HOST: modtalk.devvm
    GEM_HOME: /gem-store

browsersync:
  image: browsersync
  command: "nodejs /usr/local/bin/browser-sync start --proxy 'web:3000' --files '/app/app/**' --host 0.0.0.0 --port 80"
  links:
    - web
  expose:
    - 80
  volumes:
    - .:/app:ro
  environment:
    VIRTUAL_HOST: modtalk-sync.devvm
